project:
  type: website

website:
  title: Städte bauen, Gesellschaft formen
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://mtwente.github.io/geschichtstage25/
  repo-url: https://github.com/mtwente/geschichtstage25/
  issue-url: https://github.com/mtwente/geschichtstage25/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: Geschichtstage 2025
    tools:
      - icon: github
        url: https://github.com/mtwente/geschichtstage25/
    left:
      - text: Panel
        href: docs/panel.qmd
      - text: Beiträge
        href: docs/paper.qmd
      - text: Über
        href: docs/about.qmd

  sidebar:
    contents:
      - section: Kleingedrucktes
        href: index.qmd
        contents:
          - text: Readme
            href: README.md
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Änderungsvorschläge
            href: CONTRIBUTING.md
          - text: Lizenz (Daten)
            href: LICENSE-CCBY.md
          - text: Lizenz (Code)
            href: LICENSE-AGPL.md
          - text: Sicherheit
            href: SECURITY.md
      - href: report.md
        contents: project-management/*

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    mainfont: Jost
    fontcolor: '#181818'
    linkcolor: '#3961AA'

freeze: true

editor: visual
