project:
  type: website

website:
  title: Städte bauen, Gesellschaft formen
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://mtwente.github.io/geschichtstage25/
  repo-url: https://github.com/mtwente/geschichtstage25/
  issue-url: https://github.com/mtwente/geschichtstage25/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: geschichtstage25
    tools:
      - icon: github
        url: https://github.com/mtwente/geschichtstage25/
    left:
      - text: Readme
        href: index.qmd
      - text: Report
        href: report.md

  sidebar:
    contents:
      - section: geschichtstage25
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md
      - href: report.md
        contents: project-management/*

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true

editor: visual
