contact_links:
  - name: Are you looking for documentation on geschichtstage25?
    url: https://mtwente.github.io/geschichtstage25
    about: Please see the documentation for geschichtstage25 on its GitHub Pages page.
  - name: Do want to discuss geschichtstage25 with the community?
    url: https://github.com/mtwente/geschichtstage25/discussions
    about: Please see the discussions page for geschichtstage25.
blank_issues_enabled: true
