---
title: "Gesellschaft aus dem Zeichenautomaten"
subtitle: "Städtebau und Datenverarbeitung in der DDR"
author:
  - name: Jannik Noeske
    orcid: 0000-0001-6314-2880
    email: mail@janniknoeske.de
    affiliations:
      - Bauhaus-Universität Weimar
date: 07-09-2025
date-modified: 10-31-2024
id: "2"
lang: de
citation:
    type: standard
    event: Siebte Schweizerische Geschichtstage
    container-title: 'Städte bauen, Gesellschaft formen (Panel an den Siebten Schweizerischen Geschichtstagen)'
    author:
    - name: Jannik Noeske
    issued: 2025-07-09
---

Mit dem Aufkommen der Elektronischen Datenverarbeitung in den Hochschulen und Verwaltungen ab den 1960er Jahren wurde auch nach Anwendungen der EDV in der räumlichen Planung gesucht. Dies geschah auch in der DDR. Zunächst als Möglichkeit zur Optimierung von Standortkonzeptionen und in der Baumaterialienindustrie eingesetzt, haben sich nach 1967 eine Vielzahl von Anwendungen herausgebildet. Dazu gehörten früh auch schon Möglichkeiten der analytisch-grafischen Repräsentation von Räumen im Sinne der Kartografik, aber auch städtebauliche Entwürfe. Die gesamtgesellschaftliche Rationalisierung, die mit der gezielten Computerisierung der räumlichen Planung einherging, wird anhand des Wirtschaftsraums um Karl-Marx-Stadt/Chemnitz deutlich, der zum Experimentierfeld und Modellfall der digitalen Produktionsverhältnisse der räumlichen und gesellschaftlichen Ordnung im real existierenden Sozialismus wurde – jenseits der simplen Bilder einer kybernetischen Technikutopie. 